services:
  redis:
   image: redis:alpine
   container_name: redis-cache
   ports:
     - "6380:6379"
   networks:
     - myapp-network
   healthcheck:
    test: ["CMD", "redis-cli", "-a", "your_redis_password", "--raw", "incr", "ping"]
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest

    container_name: sqlserverdb

    ports:
      - "3535:1433"

    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=YourStrong!Passw0rd

    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - myapp-network

    healthcheck:
      test:
        [
          "CMD",
          "/opt/mssql-tools/bin/sqlcmd",
          "-S",
          "localhost",
          "-U",
          "sa",
          "-P",
          "YourStrong!Passw0rd",
          "-Q",
          "SELECT 1"
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  flowersapp.apigateway:
    image: ${DOCKER_REGISTRY-}flowersappapigateway
    build:
      context: .
      dockerfile: FlowersApp.APIGateway/Dockerfile

    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8080/health/live || exit 1"]
      interval: 15s
      timeout: 3s
      retries: 3
      start_period: 10s
    ports:
      - "9090:8080"
    networks:
      - myapp-network
    depends_on:
       - sqlserver
       - redis
       - flowersapp.auth
       - flowersapp.catalog
       - flowersapp.notification


  flowersapp.auth:
    image: ${DOCKER_REGISTRY-}flowersappauth
    build:
      context: .
      dockerfile: FlowersApp.Auth/Dockerfile

    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8080/health/live || exit 1"]
      interval: 15s
      timeout: 3s
      retries: 3
      start_period: 10s

    depends_on:
      - sqlserver
      - redis
      - rabbitmq

    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=FlowersApp.AuthDb;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True;
      - REDIS_CONNECTION_STRING=redis:6379,password=your_redis_password,abortConnect=false
      - RabbitMQ__Host=rabbitmq # <-- Add connection info for RabbitMQ
      - RabbitMQ__UserName=guest
      - RabbitMQ__Password=guest
    networks:
      - myapp-network

  flowersapp.catalog:
    image: ${DOCKER_REGISTRY-}flowersappcatalog
    build:
      context: .
      dockerfile: FlowersApp.Catalog/Dockerfile

    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8080/health/live || exit 1"]
      interval: 15s
      timeout: 3s
      retries: 3
      start_period: 10s

    depends_on:
      - sqlserver
      - redis

    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=FlowersApp.CatalogDb;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True;
      - REDIS_CONNECTION_STRING=redis:6379,password=your_redis_password,abortConnect=false
    networks:
      - myapp-network

  flowersapp.notification:
    image: ${DOCKER_REGISTRY-}flowersappnotification

    build:
      context: .
      dockerfile: FlowersApp.Notification/Dockerfile
    

    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8080/health/live || exit 1"]
      interval: 15s
      timeout: 3s
      retries: 3
      start_period: 10s
    depends_on:
      - sqlserver

    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=FlowersApp.NotificationDb;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True;
      - Firebase__CredentialsPath=/app/Secrets/flowersapp-5b282-firebase-adminsdk-fbsvc-291b465eff.json
    volumes:
      - ./Secrets/flowersapp-5b282-firebase-adminsdk-fbsvc-291b465eff.json:/app/Secrets/flowersapp-5b282-firebase-adminsdk-fbsvc-291b465eff.json:ro
    networks:
      - myapp-network

  flowersapp.cart:
    image: ${DOCKER_REGISTRY-}flowersappcart
    build:
      context: .
      dockerfile: FlowersApp.Cart/Dockerfile

    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8080/health/live || exit 1"]
      interval: 15s
      timeout: 3s
      retries: 3
      start_period: 10s

    depends_on:
      - sqlserver
      - redis
      - rabbitmq
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=FlowersApp.CartDb;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True;
      - REDIS_CONNECTION_STRING=redis:6379,password=your_redis_password,abortConnect=false
      - RabbitMQ__Host=rabbitmq # <-- Add connection info for RabbitMQ
      - RabbitMQ__UserName=guest
      - RabbitMQ__Password=guest
    networks:
      - myapp-network

  rabbitmq:                             # <-- New RabbitMQ service
    image: rabbitmq:3-management        # <-- Image with management UI [citation:4][citation:9]
    container_name: rabbitmq
    ports:
      - "5672:5672"                     # Port for your app to connect
      - "15672:15672"                   # Port for the management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest      # Set default user
      RABBITMQ_DEFAULT_PASS: guest      # Set default password
    networks:
      - myapp-network

volumes:
  sqlserver_data:


networks:
  myapp-network: