// <auto-generated />
using System;
using FlowersApp.Catalog.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;

#nullable disable

namespace FlowersApp.Catalog.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    [Migration("20260827031032_updateentities-toinherit-baseEntity")]
    partial class updateentitiestoinheritbaseEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.30")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FlowersApp.Catalog.Domain.Entities.AddressStoreAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AddressId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsUnresolved")
                        .HasColumnType("bit");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<DateTime>("ResolvedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("StoreId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AddressId")
                        .IsUnique();

                    b.HasIndex("IsUnresolved");

                    b.HasIndex("StoreId");

                    b.ToTable("AddressStoreAssignments");
                });

            modelBuilder.Entity("FlowersApp.Catalog.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IconUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IsActive", "SortOrder");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("FlowersApp.Catalog.Domain.Entities.CoverageArea", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double?>("CenterLatitude")
                        .HasColumnType("float");

                    b.Property<double?>("CenterLongitude")
                        .HasColumnType("float");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Polygon>("Geometry")
                        .HasColumnType("geography");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<double?>("RadiusMeters")
                        .HasColumnType("float");

                    b.Property<Guid>("StoreId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("StoreId");

                    b.ToTable("CoverageAreas");
                });

            modelBuilder.Entity("FlowersApp.Catalog.Domain.Entities.CoverageCity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CoverageAreaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Region")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CoverageAreaId");

                    b.ToTable("CoverageCities");
                });

            modelBuilder.Entity("FlowersApp.Catalog.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<decimal?>("DiscountPercentage")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("ImageUrls")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Includes")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.Property<Guid>("StoreId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("FlowersApp.Catalog.Domain.Entities.Store", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.ToTable("Stores");
                });

            modelBuilder.Entity("FloweryApp.Api.Domain.Entities.Occasion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IsActive", "SortOrder");

                    b.ToTable("Occasions");
                });

            modelBuilder.Entity("FloweryApp.Api.Domain.Entities.Section", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Index")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("OccasionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("OccasionId");

                    b.ToTable("Sections");

                    b.HasData(
                        new
                        {
                            Id = new Guid("bf88c20e-1167-45de-8353-831fd1ad29f0"),
                            CreatedAt = new DateTime(2026, 8, 27, 3, 10, 29, 855, DateTimeKind.Utc).AddTicks(5950),
                            CreatedBy = "System",
                            Index = 1,
                            IsActive = true,
                            IsDeleted = false,
                            Title = "Featured Products",
                            Type = 1,
                            UpdatedAt = new DateTime(2026, 8, 27, 3, 10, 29, 855, DateTimeKind.Utc).AddTicks(5955),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = new Guid("4b575dc9-16a8-4836-be8c-57d15b2d91dd"),
                            CreatedAt = new DateTime(2026, 8, 27, 3, 10, 29, 855, DateTimeKind.Utc).AddTicks(5970),
                            CreatedBy = "System",
                            Index = 2,
                            IsActive = true,
                            IsDeleted = false,
                            Title = "New Arrivals",
                            Type = 1,
                            UpdatedAt = new DateTime(2026, 8, 27, 3, 10, 29, 855, DateTimeKind.Utc).AddTicks(5971),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = new Guid("69a0135a-2d71-441b-a58b-56d3f01664fa"),
                            CreatedAt = new DateTime(2026, 8, 27, 3, 10, 29, 855, DateTimeKind.Utc).AddTicks(6000),
                            CreatedBy = "System",
                            Index = 3,
                            IsActive = true,
                            IsDeleted = false,
                            Title = "Trending Now",
                            Type = 1,
                            UpdatedAt = new DateTime(2026, 8, 27, 3, 10, 29, 855, DateTimeKind.Utc).AddTicks(6000),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = new Guid("c822a9ca-f0a6-4d0d-87a1-e096195510f4"),
                            CreatedAt = new DateTime(2026, 8, 27, 3, 10, 29, 855, DateTimeKind.Utc).AddTicks(6007),
                            CreatedBy = "System",
                            Index = 4,
                            IsActive = true,
                            IsDeleted = false,
                            Title = "Shop by Category",
                            Type = 2,
                            UpdatedAt = new DateTime(2026, 8, 27, 3, 10, 29, 855, DateTimeKind.Utc).AddTicks(6007),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = new Guid("bf193a81-68c1-4ef1-977e-656b46131e80"),
                            CreatedAt = new DateTime(2026, 8, 27, 3, 10, 29, 855, DateTimeKind.Utc).AddTicks(6014),
                            CreatedBy = "System",
                            Index = 5,
                            IsActive = true,
                            IsDeleted = false,
                            Title = "Popular Categories",
                            Type = 2,
                            UpdatedAt = new DateTime(2026, 8, 27, 3, 10, 29, 855, DateTimeKind.Utc).AddTicks(6014),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = new Guid("19a112cd-4288-47f4-81ef-1285810fd6e3"),
                            CreatedAt = new DateTime(2026, 8, 27, 3, 10, 29, 855, DateTimeKind.Utc).AddTicks(6020),
                            CreatedBy = "System",
                            Index = 6,
                            IsActive = true,
                            IsDeleted = false,
                            Title = "Special Occasions",
                            Type = 3,
                            UpdatedAt = new DateTime(2026, 8, 27, 3, 10, 29, 855, DateTimeKind.Utc).AddTicks(6021),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = new Guid("212db674-6b60-4349-9737-f43c880b7ab0"),
                            CreatedAt = new DateTime(2026, 8, 27, 3, 10, 29, 855, DateTimeKind.Utc).AddTicks(6026),
                            CreatedBy = "System",
                            Index = 7,
                            IsActive = true,
                            IsDeleted = false,
                            Title = "Holiday Collections",
                            Type = 3,
                            UpdatedAt = new DateTime(2026, 8, 27, 3, 10, 29, 855, DateTimeKind.Utc).AddTicks(6027),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = new Guid("9fac2a56-702e-4b93-9535-92816f22e0aa"),
                            CreatedAt = new DateTime(2026, 8, 27, 3, 10, 29, 855, DateTimeKind.Utc).AddTicks(6033),
                            CreatedBy = "System",
                            Index = 8,
                            IsActive = true,
                            IsDeleted = false,
                            Title = "Birthday Specials",
                            Type = 3,
                            UpdatedAt = new DateTime(2026, 8, 27, 3, 10, 29, 855, DateTimeKind.Utc).AddTicks(6034),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = new Guid("e6b0604a-11bb-48e4-973b-c8b131d335a4"),
                            CreatedAt = new DateTime(2026, 8, 27, 3, 10, 29, 855, DateTimeKind.Utc).AddTicks(6039),
                            CreatedBy = "System",
                            Index = 9,
                            IsActive = true,
                            IsDeleted = false,
                            Title = "Summer Sale",
                            Type = 4,
                            UpdatedAt = new DateTime(2026, 8, 27, 3, 10, 29, 855, DateTimeKind.Utc).AddTicks(6040),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = new Guid("b1170f83-764a-47dd-99ba-6c2e1a7d6a23"),
                            CreatedAt = new DateTime(2026, 8, 27, 3, 10, 29, 855, DateTimeKind.Utc).AddTicks(6046),
                            CreatedBy = "System",
                            Index = 10,
                            IsActive = true,
                            IsDeleted = false,
                            Title = "Mother's Day Special",
                            Type = 4,
                            UpdatedAt = new DateTime(2026, 8, 27, 3, 10, 29, 855, DateTimeKind.Utc).AddTicks(6047),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = new Guid("338596ea-909c-4d4d-9027-ffd554f062d2"),
                            CreatedAt = new DateTime(2026, 8, 27, 3, 10, 29, 855, DateTimeKind.Utc).AddTicks(6058),
                            CreatedBy = "System",
                            Index = 11,
                            IsActive = true,
                            IsDeleted = false,
                            Title = "Flash Sale",
                            Type = 4,
                            UpdatedAt = new DateTime(2026, 8, 27, 3, 10, 29, 855, DateTimeKind.Utc).AddTicks(6058),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = new Guid("3f5e4b8c-77be-494d-a6e2-b61a3d2f8501"),
                            CreatedAt = new DateTime(2026, 8, 27, 3, 10, 29, 855, DateTimeKind.Utc).AddTicks(6064),
                            CreatedBy = "System",
                            Index = 12,
                            IsActive = true,
                            IsDeleted = false,
                            Title = "Best Sellers",
                            Type = 5,
                            UpdatedAt = new DateTime(2026, 8, 27, 3, 10, 29, 855, DateTimeKind.Utc).AddTicks(6065),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = new Guid("bab9f7e3-b1ac-4e95-8d04-9f4376633080"),
                            CreatedAt = new DateTime(2026, 8, 27, 3, 10, 29, 855, DateTimeKind.Utc).AddTicks(6070),
                            CreatedBy = "System",
                            Index = 13,
                            IsActive = true,
                            IsDeleted = false,
                            Title = "Customer Favorites",
                            Type = 5,
                            UpdatedAt = new DateTime(2026, 8, 27, 3, 10, 29, 855, DateTimeKind.Utc).AddTicks(6071),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = new Guid("40c37e1c-259b-428e-9dd0-03a190d75811"),
                            CreatedAt = new DateTime(2026, 8, 27, 3, 10, 29, 855, DateTimeKind.Utc).AddTicks(6093),
                            CreatedBy = "System",
                            Index = 14,
                            IsActive = true,
                            IsDeleted = false,
                            Title = "Top Rated",
                            Type = 5,
                            UpdatedAt = new DateTime(2026, 8, 27, 3, 10, 29, 855, DateTimeKind.Utc).AddTicks(6094),
                            UpdatedBy = "System"
                        });
                });

            modelBuilder.Entity("OccasionProduct", b =>
                {
                    b.Property<Guid>("OccasionsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductsId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("OccasionsId", "ProductsId");

                    b.HasIndex("ProductsId");

                    b.ToTable("ProductOccasions", (string)null);
                });

            modelBuilder.Entity("FlowersApp.Catalog.Domain.Entities.AddressStoreAssignment", b =>
                {
                    b.HasOne("FlowersApp.Catalog.Domain.Entities.Store", "Store")
                        .WithMany()
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Store");
                });

            modelBuilder.Entity("FlowersApp.Catalog.Domain.Entities.CoverageArea", b =>
                {
                    b.HasOne("FlowersApp.Catalog.Domain.Entities.Store", "Store")
                        .WithMany("CoverageAreas")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Store");
                });

            modelBuilder.Entity("FlowersApp.Catalog.Domain.Entities.CoverageCity", b =>
                {
                    b.HasOne("FlowersApp.Catalog.Domain.Entities.CoverageArea", "CoverageArea")
                        .WithMany("Cities")
                        .HasForeignKey("CoverageAreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CoverageArea");
                });

            modelBuilder.Entity("FlowersApp.Catalog.Domain.Entities.Product", b =>
                {
                    b.HasOne("FlowersApp.Catalog.Domain.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("FloweryApp.Api.Domain.Entities.Section", b =>
                {
                    b.HasOne("FlowersApp.Catalog.Domain.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId");

                    b.HasOne("FloweryApp.Api.Domain.Entities.Occasion", "Occasion")
                        .WithMany()
                        .HasForeignKey("OccasionId");

                    b.Navigation("Category");

                    b.Navigation("Occasion");
                });

            modelBuilder.Entity("OccasionProduct", b =>
                {
                    b.HasOne("FloweryApp.Api.Domain.Entities.Occasion", null)
                        .WithMany()
                        .HasForeignKey("OccasionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FlowersApp.Catalog.Domain.Entities.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FlowersApp.Catalog.Domain.Entities.CoverageArea", b =>
                {
                    b.Navigation("Cities");
                });

            modelBuilder.Entity("FlowersApp.Catalog.Domain.Entities.Store", b =>
                {
                    b.Navigation("CoverageAreas");
                });
#pragma warning restore 612, 618
        }
    }
}
