// <auto-generated />
using System;
using FlowersApp.Catalog.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FlowersApp.Catalog.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    partial class CatalogDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.30")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FlowersApp.Catalog.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IconUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("FlowersApp.Catalog.Domain.Entities.Occasion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IsActive", "SortOrder");

                    b.ToTable("Occasions");
                });

            modelBuilder.Entity("FlowersApp.Catalog.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("DiscountPercentage")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.Property<Guid>("StoreId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("OccasionProduct", b =>
                {
                    b.Property<Guid>("OccasionsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductsId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("OccasionsId", "ProductsId");

                    b.HasIndex("ProductsId");

                    b.ToTable("ProductOccasions", (string)null);
                });

            modelBuilder.Entity("FlowersApp.Catalog.Domain.Entities.Product", b =>
                {
                    b.HasOne("FlowersApp.Catalog.Domain.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("OccasionProduct", b =>
                {
                    b.HasOne("FlowersApp.Catalog.Domain.Entities.Occasion", null)
                        .WithMany()
                        .HasForeignKey("OccasionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FlowersApp.Catalog.Domain.Entities.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FloweryApp.Api.Domain.Entities.Occasion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Occasions");
                });

            modelBuilder.Entity("FloweryApp.Api.Domain.Entities.Section", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ArabicTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Index")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("OccasionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("OccasionId");

                    b.ToTable("Sections");

                    b.HasData(
                        new
                        {
                            Id = new Guid("506aefd4-44c5-4872-98be-3227f6a7f8f4"),
                            ArabicTitle = "المنتجات المميزة",
                            CreatedAt = new DateTime(2026, 8, 21, 14, 27, 0, 619, DateTimeKind.Utc).AddTicks(7355),
                            CreatedBy = "System",
                            Index = 1,
                            IsActive = true,
                            IsDeleted = false,
                            Title = "Featured Products",
                            Type = 1,
                            UpdatedAt = new DateTime(2026, 8, 21, 14, 27, 0, 619, DateTimeKind.Utc).AddTicks(7356),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = new Guid("3329cb70-0d84-452c-afa6-3429ec467058"),
                            ArabicTitle = "الوافدون الجدد",
                            CreatedAt = new DateTime(2026, 8, 21, 14, 27, 0, 619, DateTimeKind.Utc).AddTicks(7364),
                            CreatedBy = "System",
                            Index = 2,
                            IsActive = true,
                            IsDeleted = false,
                            Title = "New Arrivals",
                            Type = 1,
                            UpdatedAt = new DateTime(2026, 8, 21, 14, 27, 0, 619, DateTimeKind.Utc).AddTicks(7364),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = new Guid("690c9830-06c9-461f-86db-0750563e4570"),
                            ArabicTitle = "الأكثر رواجاً الآن",
                            CreatedAt = new DateTime(2026, 8, 21, 14, 27, 0, 619, DateTimeKind.Utc).AddTicks(7367),
                            CreatedBy = "System",
                            Index = 3,
                            IsActive = true,
                            IsDeleted = false,
                            Title = "Trending Now",
                            Type = 1,
                            UpdatedAt = new DateTime(2026, 8, 21, 14, 27, 0, 619, DateTimeKind.Utc).AddTicks(7367),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = new Guid("805a94ae-6e18-4ddc-9f09-aa8a7bdd508c"),
                            ArabicTitle = "تسوق حسب الفئة",
                            CreatedAt = new DateTime(2026, 8, 21, 14, 27, 0, 619, DateTimeKind.Utc).AddTicks(7370),
                            CreatedBy = "System",
                            Index = 4,
                            IsActive = true,
                            IsDeleted = false,
                            Title = "Shop by Category",
                            Type = 2,
                            UpdatedAt = new DateTime(2026, 8, 21, 14, 27, 0, 619, DateTimeKind.Utc).AddTicks(7370),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = new Guid("6c0d563c-8ea8-4784-b917-f9cb4cb355e1"),
                            ArabicTitle = "الفئات الشائعة",
                            CreatedAt = new DateTime(2026, 8, 21, 14, 27, 0, 619, DateTimeKind.Utc).AddTicks(7374),
                            CreatedBy = "System",
                            Index = 5,
                            IsActive = true,
                            IsDeleted = false,
                            Title = "Popular Categories",
                            Type = 2,
                            UpdatedAt = new DateTime(2026, 8, 21, 14, 27, 0, 619, DateTimeKind.Utc).AddTicks(7374),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = new Guid("cd2251fc-22cf-43de-8e7d-5e6329be2d04"),
                            ArabicTitle = "المناسبات الخاصة",
                            CreatedAt = new DateTime(2026, 8, 21, 14, 27, 0, 619, DateTimeKind.Utc).AddTicks(7377),
                            CreatedBy = "System",
                            Index = 6,
                            IsActive = true,
                            IsDeleted = false,
                            Title = "Special Occasions",
                            Type = 3,
                            UpdatedAt = new DateTime(2026, 8, 21, 14, 27, 0, 619, DateTimeKind.Utc).AddTicks(7377),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = new Guid("69866bf1-12af-4305-8355-d1078639c8dd"),
                            ArabicTitle = "مجموعات العطلات",
                            CreatedAt = new DateTime(2026, 8, 21, 14, 27, 0, 619, DateTimeKind.Utc).AddTicks(7379),
                            CreatedBy = "System",
                            Index = 7,
                            IsActive = true,
                            IsDeleted = false,
                            Title = "Holiday Collections",
                            Type = 3,
                            UpdatedAt = new DateTime(2026, 8, 21, 14, 27, 0, 619, DateTimeKind.Utc).AddTicks(7380),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = new Guid("3cb93a91-1f69-4cba-8358-e1287eb93871"),
                            ArabicTitle = "عروض أعياد الميلاد",
                            CreatedAt = new DateTime(2026, 8, 21, 14, 27, 0, 619, DateTimeKind.Utc).AddTicks(7390),
                            CreatedBy = "System",
                            Index = 8,
                            IsActive = true,
                            IsDeleted = false,
                            Title = "Birthday Specials",
                            Type = 3,
                            UpdatedAt = new DateTime(2026, 8, 21, 14, 27, 0, 619, DateTimeKind.Utc).AddTicks(7390),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = new Guid("58e50112-7442-4c11-82be-22a5c847dd82"),
                            ArabicTitle = "تخفيضات الصيف",
                            CreatedAt = new DateTime(2026, 8, 21, 14, 27, 0, 619, DateTimeKind.Utc).AddTicks(7393),
                            CreatedBy = "System",
                            Index = 9,
                            IsActive = true,
                            IsDeleted = false,
                            Title = "Summer Sale",
                            Type = 4,
                            UpdatedAt = new DateTime(2026, 8, 21, 14, 27, 0, 619, DateTimeKind.Utc).AddTicks(7393),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = new Guid("ca118084-7bd2-492f-a8cb-4c5eed016d07"),
                            ArabicTitle = "عرض خاص بعيد الأم",
                            CreatedAt = new DateTime(2026, 8, 21, 14, 27, 0, 619, DateTimeKind.Utc).AddTicks(7396),
                            CreatedBy = "System",
                            Index = 10,
                            IsActive = true,
                            IsDeleted = false,
                            Title = "Mother's Day Special",
                            Type = 4,
                            UpdatedAt = new DateTime(2026, 8, 21, 14, 27, 0, 619, DateTimeKind.Utc).AddTicks(7396),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = new Guid("971056ae-4e7d-43ea-841f-07e8ee9971c4"),
                            ArabicTitle = "تخفيضات سريعة",
                            CreatedAt = new DateTime(2026, 8, 21, 14, 27, 0, 619, DateTimeKind.Utc).AddTicks(7398),
                            CreatedBy = "System",
                            Index = 11,
                            IsActive = true,
                            IsDeleted = false,
                            Title = "Flash Sale",
                            Type = 4,
                            UpdatedAt = new DateTime(2026, 8, 21, 14, 27, 0, 619, DateTimeKind.Utc).AddTicks(7399),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = new Guid("67b3c747-fdeb-4c99-950c-b364c89dce02"),
                            ArabicTitle = "الأكثر مبيعاً",
                            CreatedAt = new DateTime(2026, 8, 21, 14, 27, 0, 619, DateTimeKind.Utc).AddTicks(7401),
                            CreatedBy = "System",
                            Index = 12,
                            IsActive = true,
                            IsDeleted = false,
                            Title = "Best Sellers",
                            Type = 5,
                            UpdatedAt = new DateTime(2026, 8, 21, 14, 27, 0, 619, DateTimeKind.Utc).AddTicks(7402),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = new Guid("31482c92-c341-476f-bc36-ed98294535be"),
                            ArabicTitle = "المفضلات لدى العملاء",
                            CreatedAt = new DateTime(2026, 8, 21, 14, 27, 0, 619, DateTimeKind.Utc).AddTicks(7406),
                            CreatedBy = "System",
                            Index = 13,
                            IsActive = true,
                            IsDeleted = false,
                            Title = "Customer Favorites",
                            Type = 5,
                            UpdatedAt = new DateTime(2026, 8, 21, 14, 27, 0, 619, DateTimeKind.Utc).AddTicks(7406),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = new Guid("f4a5d895-9bcc-4ec5-a568-2ae1403c03d2"),
                            ArabicTitle = "الأعلى تقييماً",
                            CreatedAt = new DateTime(2026, 8, 21, 14, 27, 0, 619, DateTimeKind.Utc).AddTicks(7409),
                            CreatedBy = "System",
                            Index = 14,
                            IsActive = true,
                            IsDeleted = false,
                            Title = "Top Rated",
                            Type = 5,
                            UpdatedAt = new DateTime(2026, 8, 21, 14, 27, 0, 619, DateTimeKind.Utc).AddTicks(7409),
                            UpdatedBy = "System"
                        });
                });

            modelBuilder.Entity("FloweryApp.Api.Domain.Entities.Section", b =>
                {
                    b.HasOne("FlowersApp.Catalog.Domain.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId");

                    b.HasOne("FloweryApp.Api.Domain.Entities.Occasion", "Occasion")
                        .WithMany()
                        .HasForeignKey("OccasionId");

                    b.Navigation("Category");

                    b.Navigation("Occasion");
                });
#pragma warning restore 612, 618
        }
    }
}
