// <auto-generated />
using System;
using FlowersApp.Catalog.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FlowersApp.Catalog.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    partial class CatalogDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.30")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FlowersApp.Catalog.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IconUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IsActive", "SortOrder");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("FlowersApp.Catalog.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("DiscountPercentage")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.Property<Guid>("StoreId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("FloweryApp.Api.Domain.Entities.Occasion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IsActive", "SortOrder");

                    b.ToTable("Occasions");
                });

            modelBuilder.Entity("FloweryApp.Api.Domain.Entities.Section", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Index")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("OccasionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("OccasionId");

                    b.ToTable("Sections");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6505e5a6-2e80-4020-b682-2bd995949177"),
                            CreatedAt = new DateTime(2026, 8, 21, 17, 35, 11, 173, DateTimeKind.Utc).AddTicks(8738),
                            CreatedBy = "System",
                            Index = 1,
                            IsActive = true,
                            IsDeleted = false,
                            Title = "Featured Products",
                            Type = 1,
                            UpdatedAt = new DateTime(2026, 8, 21, 17, 35, 11, 173, DateTimeKind.Utc).AddTicks(8740),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = new Guid("f72a7fd5-0c0c-491a-b40b-a396579ad06a"),
                            CreatedAt = new DateTime(2026, 8, 21, 17, 35, 11, 173, DateTimeKind.Utc).AddTicks(8745),
                            CreatedBy = "System",
                            Index = 2,
                            IsActive = true,
                            IsDeleted = false,
                            Title = "New Arrivals",
                            Type = 1,
                            UpdatedAt = new DateTime(2026, 8, 21, 17, 35, 11, 173, DateTimeKind.Utc).AddTicks(8746),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = new Guid("fc11c499-7f4e-4445-ae4f-9e750364de8e"),
                            CreatedAt = new DateTime(2026, 8, 21, 17, 35, 11, 173, DateTimeKind.Utc).AddTicks(8748),
                            CreatedBy = "System",
                            Index = 3,
                            IsActive = true,
                            IsDeleted = false,
                            Title = "Trending Now",
                            Type = 1,
                            UpdatedAt = new DateTime(2026, 8, 21, 17, 35, 11, 173, DateTimeKind.Utc).AddTicks(8748),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = new Guid("6234ab21-d8c0-4009-a71b-f305ebb76378"),
                            CreatedAt = new DateTime(2026, 8, 21, 17, 35, 11, 173, DateTimeKind.Utc).AddTicks(8751),
                            CreatedBy = "System",
                            Index = 4,
                            IsActive = true,
                            IsDeleted = false,
                            Title = "Shop by Category",
                            Type = 2,
                            UpdatedAt = new DateTime(2026, 8, 21, 17, 35, 11, 173, DateTimeKind.Utc).AddTicks(8752),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = new Guid("9ff9f9e5-515b-4e34-b371-c53486b92e5c"),
                            CreatedAt = new DateTime(2026, 8, 21, 17, 35, 11, 173, DateTimeKind.Utc).AddTicks(8754),
                            CreatedBy = "System",
                            Index = 5,
                            IsActive = true,
                            IsDeleted = false,
                            Title = "Popular Categories",
                            Type = 2,
                            UpdatedAt = new DateTime(2026, 8, 21, 17, 35, 11, 173, DateTimeKind.Utc).AddTicks(8754),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = new Guid("d0b082c1-5e07-494b-9211-359061a0fd7f"),
                            CreatedAt = new DateTime(2026, 8, 21, 17, 35, 11, 173, DateTimeKind.Utc).AddTicks(8806),
                            CreatedBy = "System",
                            Index = 6,
                            IsActive = true,
                            IsDeleted = false,
                            Title = "Special Occasions",
                            Type = 3,
                            UpdatedAt = new DateTime(2026, 8, 21, 17, 35, 11, 173, DateTimeKind.Utc).AddTicks(8806),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = new Guid("bf73b2a9-d8dd-49f6-88a5-00c5394b238d"),
                            CreatedAt = new DateTime(2026, 8, 21, 17, 35, 11, 173, DateTimeKind.Utc).AddTicks(8810),
                            CreatedBy = "System",
                            Index = 7,
                            IsActive = true,
                            IsDeleted = false,
                            Title = "Holiday Collections",
                            Type = 3,
                            UpdatedAt = new DateTime(2026, 8, 21, 17, 35, 11, 173, DateTimeKind.Utc).AddTicks(8810),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = new Guid("00f62b00-da4a-43d9-8979-fd963db01dee"),
                            CreatedAt = new DateTime(2026, 8, 21, 17, 35, 11, 173, DateTimeKind.Utc).AddTicks(8820),
                            CreatedBy = "System",
                            Index = 8,
                            IsActive = true,
                            IsDeleted = false,
                            Title = "Birthday Specials",
                            Type = 3,
                            UpdatedAt = new DateTime(2026, 8, 21, 17, 35, 11, 173, DateTimeKind.Utc).AddTicks(8820),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = new Guid("61b984ef-8498-4666-8e4c-0fc7de161eee"),
                            CreatedAt = new DateTime(2026, 8, 21, 17, 35, 11, 173, DateTimeKind.Utc).AddTicks(8823),
                            CreatedBy = "System",
                            Index = 9,
                            IsActive = true,
                            IsDeleted = false,
                            Title = "Summer Sale",
                            Type = 4,
                            UpdatedAt = new DateTime(2026, 8, 21, 17, 35, 11, 173, DateTimeKind.Utc).AddTicks(8823),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = new Guid("b444ddf3-4ae0-4a01-9ea3-cedfd3bba197"),
                            CreatedAt = new DateTime(2026, 8, 21, 17, 35, 11, 173, DateTimeKind.Utc).AddTicks(8826),
                            CreatedBy = "System",
                            Index = 10,
                            IsActive = true,
                            IsDeleted = false,
                            Title = "Mother's Day Special",
                            Type = 4,
                            UpdatedAt = new DateTime(2026, 8, 21, 17, 35, 11, 173, DateTimeKind.Utc).AddTicks(8826),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = new Guid("6741db93-9e3b-4bab-a09c-a383ea475da6"),
                            CreatedAt = new DateTime(2026, 8, 21, 17, 35, 11, 173, DateTimeKind.Utc).AddTicks(8829),
                            CreatedBy = "System",
                            Index = 11,
                            IsActive = true,
                            IsDeleted = false,
                            Title = "Flash Sale",
                            Type = 4,
                            UpdatedAt = new DateTime(2026, 8, 21, 17, 35, 11, 173, DateTimeKind.Utc).AddTicks(8829),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = new Guid("47afe3b9-f7a6-44fd-9f93-7553124bee1b"),
                            CreatedAt = new DateTime(2026, 8, 21, 17, 35, 11, 173, DateTimeKind.Utc).AddTicks(8831),
                            CreatedBy = "System",
                            Index = 12,
                            IsActive = true,
                            IsDeleted = false,
                            Title = "Best Sellers",
                            Type = 5,
                            UpdatedAt = new DateTime(2026, 8, 21, 17, 35, 11, 173, DateTimeKind.Utc).AddTicks(8832),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = new Guid("74ec7f26-d798-4a76-89bf-268f9faeb6cb"),
                            CreatedAt = new DateTime(2026, 8, 21, 17, 35, 11, 173, DateTimeKind.Utc).AddTicks(8834),
                            CreatedBy = "System",
                            Index = 13,
                            IsActive = true,
                            IsDeleted = false,
                            Title = "Customer Favorites",
                            Type = 5,
                            UpdatedAt = new DateTime(2026, 8, 21, 17, 35, 11, 173, DateTimeKind.Utc).AddTicks(8834),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = new Guid("4dcfa0eb-66d1-464f-baca-d6322f59cab6"),
                            CreatedAt = new DateTime(2026, 8, 21, 17, 35, 11, 173, DateTimeKind.Utc).AddTicks(8836),
                            CreatedBy = "System",
                            Index = 14,
                            IsActive = true,
                            IsDeleted = false,
                            Title = "Top Rated",
                            Type = 5,
                            UpdatedAt = new DateTime(2026, 8, 21, 17, 35, 11, 173, DateTimeKind.Utc).AddTicks(8837),
                            UpdatedBy = "System"
                        });
                });

            modelBuilder.Entity("OccasionProduct", b =>
                {
                    b.Property<Guid>("OccasionsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductsId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("OccasionsId", "ProductsId");

                    b.HasIndex("ProductsId");

                    b.ToTable("ProductOccasions", (string)null);
                });

            modelBuilder.Entity("FlowersApp.Catalog.Domain.Entities.Product", b =>
                {
                    b.HasOne("FlowersApp.Catalog.Domain.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Category");
                });

            modelBuilder.Entity("FloweryApp.Api.Domain.Entities.Section", b =>
                {
                    b.HasOne("FlowersApp.Catalog.Domain.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId");

                    b.HasOne("FloweryApp.Api.Domain.Entities.Occasion", "Occasion")
                        .WithMany()
                        .HasForeignKey("OccasionId");

                    b.Navigation("Category");

                    b.Navigation("Occasion");
                });

            modelBuilder.Entity("OccasionProduct", b =>
                {
                    b.HasOne("FloweryApp.Api.Domain.Entities.Occasion", null)
                        .WithMany()
                        .HasForeignKey("OccasionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FlowersApp.Catalog.Domain.Entities.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
