// <auto-generated />
using System;
using FlowersApp.Catalog.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FlowersApp.Catalog.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    partial class CatalogDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.30")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FlowersApp.Catalog.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IconUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IsActive", "SortOrder");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("FlowersApp.Catalog.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<decimal?>("DiscountPercentage")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("ImageUrls")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Includes")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.Property<Guid>("StoreId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("FloweryApp.Api.Domain.Entities.Occasion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IsActive", "SortOrder");

                    b.ToTable("Occasions");
                });

            modelBuilder.Entity("FloweryApp.Api.Domain.Entities.Section", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Index")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("OccasionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("OccasionId");

                    b.ToTable("Sections");

                    b.HasData(
                        new
                        {
                            Id = new Guid("24ba8588-8851-4279-b595-2e7bf535365d"),
                            CreatedAt = new DateTime(2026, 8, 24, 21, 48, 18, 842, DateTimeKind.Utc).AddTicks(7138),
                            CreatedBy = "System",
                            Index = 1,
                            IsActive = true,
                            IsDeleted = false,
                            Title = "Featured Products",
                            Type = 1,
                            UpdatedAt = new DateTime(2026, 8, 24, 21, 48, 18, 842, DateTimeKind.Utc).AddTicks(7141),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = new Guid("1cf0812e-0b42-4ce7-b052-1a3b3ce9aca8"),
                            CreatedAt = new DateTime(2026, 8, 24, 21, 48, 18, 842, DateTimeKind.Utc).AddTicks(7156),
                            CreatedBy = "System",
                            Index = 2,
                            IsActive = true,
                            IsDeleted = false,
                            Title = "New Arrivals",
                            Type = 1,
                            UpdatedAt = new DateTime(2026, 8, 24, 21, 48, 18, 842, DateTimeKind.Utc).AddTicks(7157),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = new Guid("fdd1c93f-58c5-4194-ad6c-77c3d59614a5"),
                            CreatedAt = new DateTime(2026, 8, 24, 21, 48, 18, 842, DateTimeKind.Utc).AddTicks(7160),
                            CreatedBy = "System",
                            Index = 3,
                            IsActive = true,
                            IsDeleted = false,
                            Title = "Trending Now",
                            Type = 1,
                            UpdatedAt = new DateTime(2026, 8, 24, 21, 48, 18, 842, DateTimeKind.Utc).AddTicks(7160),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = new Guid("95eaf337-4f14-446d-b01d-9e4c2e8d9e9b"),
                            CreatedAt = new DateTime(2026, 8, 24, 21, 48, 18, 842, DateTimeKind.Utc).AddTicks(7163),
                            CreatedBy = "System",
                            Index = 4,
                            IsActive = true,
                            IsDeleted = false,
                            Title = "Shop by Category",
                            Type = 2,
                            UpdatedAt = new DateTime(2026, 8, 24, 21, 48, 18, 842, DateTimeKind.Utc).AddTicks(7163),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = new Guid("5b8ae00f-9a29-4f6e-a898-2f41821263af"),
                            CreatedAt = new DateTime(2026, 8, 24, 21, 48, 18, 842, DateTimeKind.Utc).AddTicks(7166),
                            CreatedBy = "System",
                            Index = 5,
                            IsActive = true,
                            IsDeleted = false,
                            Title = "Popular Categories",
                            Type = 2,
                            UpdatedAt = new DateTime(2026, 8, 24, 21, 48, 18, 842, DateTimeKind.Utc).AddTicks(7166),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = new Guid("b394f359-8703-4884-8493-2e0d9a1f1fa8"),
                            CreatedAt = new DateTime(2026, 8, 24, 21, 48, 18, 842, DateTimeKind.Utc).AddTicks(7169),
                            CreatedBy = "System",
                            Index = 6,
                            IsActive = true,
                            IsDeleted = false,
                            Title = "Special Occasions",
                            Type = 3,
                            UpdatedAt = new DateTime(2026, 8, 24, 21, 48, 18, 842, DateTimeKind.Utc).AddTicks(7170),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = new Guid("e8730c7f-c2de-4574-a39c-a919a220c8d6"),
                            CreatedAt = new DateTime(2026, 8, 24, 21, 48, 18, 842, DateTimeKind.Utc).AddTicks(7172),
                            CreatedBy = "System",
                            Index = 7,
                            IsActive = true,
                            IsDeleted = false,
                            Title = "Holiday Collections",
                            Type = 3,
                            UpdatedAt = new DateTime(2026, 8, 24, 21, 48, 18, 842, DateTimeKind.Utc).AddTicks(7172),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = new Guid("39e4e8b0-bb2d-4979-b019-5e4cd0e38dda"),
                            CreatedAt = new DateTime(2026, 8, 24, 21, 48, 18, 842, DateTimeKind.Utc).AddTicks(7176),
                            CreatedBy = "System",
                            Index = 8,
                            IsActive = true,
                            IsDeleted = false,
                            Title = "Birthday Specials",
                            Type = 3,
                            UpdatedAt = new DateTime(2026, 8, 24, 21, 48, 18, 842, DateTimeKind.Utc).AddTicks(7176),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = new Guid("fac654cc-fc1e-44c0-a5fa-8a10cc435d9c"),
                            CreatedAt = new DateTime(2026, 8, 24, 21, 48, 18, 842, DateTimeKind.Utc).AddTicks(7179),
                            CreatedBy = "System",
                            Index = 9,
                            IsActive = true,
                            IsDeleted = false,
                            Title = "Summer Sale",
                            Type = 4,
                            UpdatedAt = new DateTime(2026, 8, 24, 21, 48, 18, 842, DateTimeKind.Utc).AddTicks(7179),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = new Guid("e05dc921-8aad-414d-b149-6c7bcc7bc65e"),
                            CreatedAt = new DateTime(2026, 8, 24, 21, 48, 18, 842, DateTimeKind.Utc).AddTicks(7185),
                            CreatedBy = "System",
                            Index = 10,
                            IsActive = true,
                            IsDeleted = false,
                            Title = "Mother's Day Special",
                            Type = 4,
                            UpdatedAt = new DateTime(2026, 8, 24, 21, 48, 18, 842, DateTimeKind.Utc).AddTicks(7185),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = new Guid("ba192ef3-4de8-4cbb-86c8-61ccdc498158"),
                            CreatedAt = new DateTime(2026, 8, 24, 21, 48, 18, 842, DateTimeKind.Utc).AddTicks(7188),
                            CreatedBy = "System",
                            Index = 11,
                            IsActive = true,
                            IsDeleted = false,
                            Title = "Flash Sale",
                            Type = 4,
                            UpdatedAt = new DateTime(2026, 8, 24, 21, 48, 18, 842, DateTimeKind.Utc).AddTicks(7188),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = new Guid("d174b909-6f35-4f1b-ab42-f09c28a64112"),
                            CreatedAt = new DateTime(2026, 8, 24, 21, 48, 18, 842, DateTimeKind.Utc).AddTicks(7290),
                            CreatedBy = "System",
                            Index = 12,
                            IsActive = true,
                            IsDeleted = false,
                            Title = "Best Sellers",
                            Type = 5,
                            UpdatedAt = new DateTime(2026, 8, 24, 21, 48, 18, 842, DateTimeKind.Utc).AddTicks(7291),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = new Guid("51818fd0-5ec5-43a1-9d03-9a53fc09f4c0"),
                            CreatedAt = new DateTime(2026, 8, 24, 21, 48, 18, 842, DateTimeKind.Utc).AddTicks(7294),
                            CreatedBy = "System",
                            Index = 13,
                            IsActive = true,
                            IsDeleted = false,
                            Title = "Customer Favorites",
                            Type = 5,
                            UpdatedAt = new DateTime(2026, 8, 24, 21, 48, 18, 842, DateTimeKind.Utc).AddTicks(7294),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = new Guid("cf2f2830-9381-4fa8-8c35-d9facf58901e"),
                            CreatedAt = new DateTime(2026, 8, 24, 21, 48, 18, 842, DateTimeKind.Utc).AddTicks(7297),
                            CreatedBy = "System",
                            Index = 14,
                            IsActive = true,
                            IsDeleted = false,
                            Title = "Top Rated",
                            Type = 5,
                            UpdatedAt = new DateTime(2026, 8, 24, 21, 48, 18, 842, DateTimeKind.Utc).AddTicks(7297),
                            UpdatedBy = "System"
                        });
                });

            modelBuilder.Entity("OccasionProduct", b =>
                {
                    b.Property<Guid>("OccasionsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductsId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("OccasionsId", "ProductsId");

                    b.HasIndex("ProductsId");

                    b.ToTable("ProductOccasions", (string)null);
                });

            modelBuilder.Entity("FlowersApp.Catalog.Domain.Entities.Product", b =>
                {
                    b.HasOne("FlowersApp.Catalog.Domain.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("FloweryApp.Api.Domain.Entities.Section", b =>
                {
                    b.HasOne("FlowersApp.Catalog.Domain.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId");

                    b.HasOne("FloweryApp.Api.Domain.Entities.Occasion", "Occasion")
                        .WithMany()
                        .HasForeignKey("OccasionId");

                    b.Navigation("Category");

                    b.Navigation("Occasion");
                });

            modelBuilder.Entity("OccasionProduct", b =>
                {
                    b.HasOne("FloweryApp.Api.Domain.Entities.Occasion", null)
                        .WithMany()
                        .HasForeignKey("OccasionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FlowersApp.Catalog.Domain.Entities.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
